"""create the email column 

Revision ID: 73147e058e37
Revises: a8a7b67179c8
Create Date: 2021-11-03 12:45:54.042144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73147e058e37'
down_revision = 'a8a7b67179c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
